services:
  db:
    image: postgres:13
    env_file:
       - ./.env
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn config.wsgi --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
       - ./.env

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    env_file:
       - ./.env
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A config beat --loglevel=info
    env_file:
       - ./.env
    depends_on:
      - redis
      - db

volumes:
  postgres_data: