# Используем базовый образ Python
FROM python:3.12-slim

# Рабочая директория внутри контейнера
WORKDIR /code

# Копируем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект
COPY . .

# Запускаем Django сервер
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
